# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Magic Nix Cache (Faster Builds)
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run Nix checks
        run: nix flake check -L
